version: '2'

services:
  hub:
    image: selenium/hub
    ports:
    - 4444:4444/tcp
    network_mode: 'bridge'
    restart: on-failure:5
    mem_limit: 268435456
    security_opt:
    - no-new-privileges

  chrome:
    image: selenium/node-chrome-debug
    ports:
    - 5900:5900/tcp
    environment:
      SCREEN_WIDTH: '1600'
      SCREEN_HEIGHT: '1200'
    volumes:
    - /dev/shm:/dev/shm
    links:
    - hub
    network_mode: 'bridge'
    restart: on-failure:5
    mem_limit: 1073741824
    security_opt:
    - no-new-privileges

  firefox:
    image: selenium/node-firefox-debug
    ports:
    - 5901:5900/tcp
    environment:
      SCREEN_WIDTH: '1600'
      SCREEN_HEIGHT: '1200'
    links:
    - hub
    network_mode: 'bridge'
    restart: on-failure:5
    mem_limit: 1073741824
    security_opt:
    - no-new-privileges
